# DEVELOPMENT CONFIGURATION
services:

  bugdb:
    container_name: bugdb
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./bugdb/initdb:/docker-entrypoint-initdb.d/

  bugweb:
    container_name: bugweb
    build: ./bugweb
    volumes:
      - ./bugweb:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - bugdb
    command: ./entrypoint.sh

  bugbot:
    container_name: bugbot
    volumes:
      - ./bugbot:/app
    build: ./bugbot
    env_file:
      - .env
    depends_on:
      - bugdb
    command: python bugbot.py

volumes:
  postgres_data:
